package.json

This patch updates some deps with non-major version changes, and also
relaxes the versioning used in the package.json to allow bugfix
releases.
Using pinned versions is probably a well intentioned but naive
restriction that prevents a consumer from automatically receiving
security fixes unless the package author approves them, which can take a
long time. Pinned dependencies don't work in Node-land anyway, as NPM
will happily give you multiple copies of a specific library at different
versions, and pins do also not prevent transitive dependencies from
including version ranges anyway. For these reasons, it is more a
security risk than a reliability insurance.

Update dependencies and remove fixed versioning

---

lib/system.js

When running `pkg` in a Docker Desktop ARM-image container on an Intel laptop, using `binfmt_misc` / QEMU architecture emulation, `/proc/cpuinfo` reports the Intel processor rather than the emulated ARM processor. The existing architecture detection then fails. Also, the existing detection code does not support arm64 (e.g. the Raspberry Pi 4), reporting `armv6` instead.

Improve ARM architecture detection: arm64 and armv7

---

lib/build.js

…via the MAKE_JOB_COUNT environment variable
This should in general speed up the building of node.

Allow configuring number of processes used for compiling.

---

patches/node.v14.16.0.cpp.patch
patches/patches.json

Updated patch for 14.16.0
Closes #117

Add support for 14.16.0

---

patches/node.v14.16.0.cpp.patch

Fixes: #118
Needs: vercel/pkg#1059

patches: drop internalModuleReadJSON hack of v14.16.0

---

lib/bin.ts
lib/index.ts
package.json
yarn.lock

Much better with "--help" and default values. It also allows us to set CLI
options with PKG_FETCH_OPTION_. For instance:
PKG_FETCH_OPTION_n=node14
PKG_FETCH_OPTION_b=true
builds Node 14 for the host platform and arch. might be useful for Dockerfile-scripts.
We can add descriptions in a later change to make this even more user-friendly.
$ pkg-fetch -h
Options:
-n, --node-range                                  [string] [default: "latest"]
-p, --platform                                     [string] [default: "linux"]
-a, --arch                                           [string] [default: "x64"]
-f, --force-fetch                                                    [boolean]
-b, --force-build                                                    [boolean]
-v, --version      Show version number …

Improve CLI interface

---

lib/index.ts
lib/requests.ts
package.json
typings/request-progress.d.ts
yarn.lock

Per suggestion of https://github.com/vercel/pkg-fetch/pull/144#pullrequestreview-625308160.

Migrate from requests to axios

---

lib/build.ts
lib/index.ts

To test on Ubuntu (amd64 host): 
```bash
$ sudo apt install build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
$ export CC=/usr/bin/aarch64-linux-gnu-gcc CXX=/usr/bin/aarch64-linux-gnu-g++ AR=/usr/bin/aarch64-linux-gnu-ar NM=/usr/bin/aarch64-linux-gnu-nm READELF=/usr/bin/aarch64-linux-gnu-readelf
$ export CC_host=/usr/bin/gcc CXX_host=/usr/bin/g++ AR_host=/usr/bin/ar NM_host=/usr/bin/nm READELF_host=/usr/bin/readelf
$ pkg-fetch --force-build --arch arm64
```

Allow cross compiling

---

lib/build.ts

To allow us to workaround a path problem with older Node versions
and some Windows environments.

Allow to override build path with PKG_BUILD_PATH

---

.github/workflows/build-linux.yml
.github/workflows/build-macos.yml
.github/workflows/build-windows.yml
Dockerfile.linux

Linux: https://github.com/jesec/pkg-fetch/actions/runs/711723135
Windows: https://github.com/jesec/pkg-fetch/actions/runs/711723405
* Node < 14 does not support cross compilation for win-arm64
macOS: https://github.com/jesec/pkg-fetch/actions/runs/711723492
* There is no support for cross compilation on macOS. Plus, the signing issue with Apple Silicon: https://github.com/jesec/pkg-fetch/releases/tag/v2.7 . 
This should allow us to release 3.0.
@leerob , after we merge this change, please:
1. Bump and tag version. Build and release to npm.
1. Go to `Actions` and run binary workflows.
1. Fetch the binaries from `Actions` after workflows finish.
1. Rename from `built-*` to `node-*`. 
1. Upload them to a `v3.0` release. (strictly vMAJOR.MINOR here. no patch. patch releases are not expected …

CI: add binary workflows

---

package.json

So we can use proper types in `pkg`.

Include TypeScript types in package

---

lib/log.ts

Otherwise we can't use "linuxstatic" due to progress bar out of range...

log: expand progress bar width to 35

---

package.json

CI workflows skip existing binaries in the same minor version. However,
some changes require us to rebuild and replace binaries.
As such, bump the minor version and create a Git tag to store the binaries.
Binaries to be carried over from v3.0:
- alpine, linux, linuxstatic and win
macOS ones would be recompiled due to 5d2bc3bb2, and Node 16.0.0
binaries will be dropped in v3.1.
No npm release is required for this change. We will do that after
binaries are compiled and hashes are updated.

Working on v3.1.0

---

patches/node.v16.1.0.cpp.patch

Apparently with nodejs/node@54dfdbccc and our addition of a bootstrap
script entry, we hit some sorts of limits on Windows platform.
Mysteriously a command starts to fail. I suspect that we happen to
reach the maximum command line argument length on Windows.
This change is a quick hack to bring the command below the limit. It
does not change the functionality in any way. Upstream is going to
notice this issue soon, when they add another internal JavaScript
function.

patches: workaround the js2c command issue with node16-win

---

lib/expected.ts

- replaced macOS binaries due to 5d2bc3b
- node(8/10/12/14)-(alpine/linux/linuxstatic/win) carried over from v3.0
- added Node v16.1 binaries
- added macos-arm64 binaries (Node 14/16 only)

expected: update hashes for v3.1

---

.github/workflows/build-linux.yml
Dockerfile.linuxcross

Recently it comes to my attention that Github Actions image installs
experimental C++ standard library from an unsupported PPA, which
effectively breaks assumptions of binary compatibility for the OS
(in this case, Ubuntu 18.04+).
Unfortunately, as a result, the Github Actions environment can no
longer be trusted to compile proper binaries.
This change adds a Dockerfile that composes a proper Ubuntu 18.04
environment from official "ubuntu:bionic" image, and builds Node
binaries in it.
Refs: actions/virtual-environments#3376, actions/virtual-environments#3432, actions/virtual-environments#3459

CI: use Docker to build binaries for linux-arm64

---

lib/expected.ts

- node8 carried over from v3.1
- node(10/12/14/16)-(alpine/linuxstatic/win) carried over from v3.1
- node(10/12/14/16)-linux-x64 carried over from v3.1
- macOS binaries replaced due to 93de534a9
- linux-arm64 binaries replaced due to 6de6de36a
- linuxstatic-armv7 binaries added (#194, @Hypfer)

expected: update hashes for v3.2

---

patches/node.v12.22.7.cpp.patch
patches/node.v14.18.1.cpp.patch
patches/node.v16.13.0.cpp.patch
patches/patches.json

patches: do not optimize "BAKERY" placeholder out (GCC ver.), bump to 16.13.0

---

Dockerfile.alpine
Dockerfile.linux
lib/build.ts
lib/places.ts
package.json
yarn.lock

Bug: #204, #212
For #212 use case, the user may place the source archive and its `.sha256sum` to `$PKG_CACHE_PATH/node` (by default, PKG_CACHE_PATH is `~/.pkg-cache`), if the network connection is restricted.

build: fetch Node.js sources from tar.gz archive instead of Git

---

patches/node.v14.21.1.cpp.patch
patches/node.v16.18.1.cpp.patch
patches/node.v18.12.1.cpp.patch
patches/patches.json

fixes #259
all patches apply cleanly, but this is having some difficulty building locally. I tried building from v18.12.1 in vanilla node and it also fails, so I'm not sure if it's some issue with my build environment, but considering they are the same failure for vanilla as pkg-fetch, I'll submit this PR.
Here is the error output in case anybody has any ideas:
```
v8_initializers.vcxproj -> ..\..\out\Release\lib\v8_initializers.lib
embedded-file-writer.cc
mksnapshot.cc
C:\git\node\deps\v8\src\base\bits.h(340,31): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\git\node\tools\v8_gypfiles\mksnapshot.vcxproj]
C:\git\node\deps\v8\src\base\bits.h(340,31): warning C4146: unary minus operator applied to unsigned type, result still unsigned …
```

patches: bump to 18.12.1, 16.18.1 and 14.21.1

---

.github/workflows/ci.yml
README.md
lib/apply-patches.ts
lib/build.ts
lib/index.ts
package.json
patches/node.v10.24.1.cpp.patch
scripts/test_patch.sh

In trying to apply patches for new versions, I found it helpful to be able to iterate a bit faster when adjusting the patches without having to run a full build each time. I also thought it might be helpful to add some basic documentation to show folks how to do this themselves. Hopefully this enables more hands to help keep this very useful library up to date.
Please let me know if you think anything can be improved. I appreciate the feedback.

Add applyPatches script and some basic patch documentation

---

patches/node.v18.13.0.cpp.patch

Trying to cobble together the fixes for the `v18.13.0` patch.
For starters, the identity of `v8_script` seemed to change from a `MaybeLocal<UnboundScript>` to be a `Local<UnboundScript>` so we should no longer call `toLocalChecked()` on it.
Other changes...I do not know, I'll build from here and see where that leads.
As usual, I am totally open to feedback and advice on this.
This is meant to fix #272

patches: fix toLocalChecked use in 18.13.0

---

.github/workflows/arm64-alpine.yml
.github/workflows/arm64-linux.yml
.github/workflows/arm64-linuxstatic.yml
.github/workflows/arm64-macos.yml
.github/workflows/build-alpine.yml
.github/workflows/build-linux.yml
.github/workflows/build-linuxstatic.yml
.github/workflows/build-macos.yml
.github/workflows/build-windows.yml
.github/workflows/ci.yml
lib/build.ts
patches/node.v19.6.0.cpp.patch
patches/patches.json

I prepared a patch for node 19.6 and then linked/tested it within our project. These seem to work based on our usage.

patches: add patch for node 19.6

---

Dockerfile.linux

Related to #264 and fixes binary build failures that try to do `yum install nodejs @ 18.12.1` since the glibc requirements of _that_ nodejs package are >= 2.28, and it appears the nodejs we need in the environment of the Docker container is used for bootstrapping `pkg-fetch` to do the actual build
This should work as a workaround for now until a decision is made regarding whether to build on a newer runner for future node.js versions.

dockerfile.linux: use Node.js 16.x to avoid glibc issues

---

patches/node.v18.15.0.cpp.patch
patches/node.v19.8.1.cpp.patch

As described in https://github.com/vercel/pkg-fetch/issues/282 there is an issue with workers starting from node.js 18.14.1. This fix solves this issue for 18.15.0 as well as 19.8.1

fix: patch issues with workers #282
